header:
  heading: fulldev-starter
  links:
    - text: Home
      href: /
    - text: Fulldev-ui
      href: 'https://ui.full.dev'
    - text: Components
      href: 'https://ui.full.dev/typography/heading/'
    - text: Blocks
      href: 'https://ui.full.dev/blocks'
  buttons:
    - icon: brand-github
      href: 'https://github.com/fulldotdev/starter'
    - text: README
      href: 'https://github.com/fulldotdev/starter/blob/main/README.md'
  drawer:
    links:
      - text: Home
        href: '/'
      - text: Fulldev-ui
        href: 'https://ui.full.dev'
      - text: Components
        href: 'https://ui.full.dev/typography/heading/'
      - text: Blocks
        href: 'https://ui.full.dev/blocks'

footer:
  heading: fulldev-starter
  text: Supercharging content-driven website development
  structure: spread
  columns:
    - heading: Resources
      links:
        - text: Home
          href: /
        - text: Components
          href: 'https://ui.full.dev/typography/heading/'
        - text: Blocks
          href: 'https://ui.full.dev/blocks'
        - text: README
          href: 'https://github.com/fulldotdev/starter/blob/main/README.md'
