paths:
  uploads: public/assets
  uploads_filename:
  static: public
  collections:
collections_config:
  pages:
    path: src/content/pages
    output: true
    url: /[full_slug]/
    filter:
    name:
    description: ''
    icon: wysiwyg
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables:
    _enabled_editors:
      - visual
    _inputs:
    _select_data:
    _structures:
    create:
      path: '[relative_base_path]/{heading|slugify}.md.'
      extra_data:
      publish_to:
      _inputs:
      _select_data:
      _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: src/schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: true
        remove_extra_inputs: false
        icon: notes
  reviews:
    path: src/content/pages/reviews
    output: true
    url: /[full_slug]/
    name:
    description: ''
    icon: wysiwyg
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables:
    _enabled_editors:
      - visual
    _inputs:
    _select_data:
    _structures:
    create:
      path: '[relative_base_path]/{heading|slugify}.md.'
      extra_data:
      publish_to:
      _inputs:
      _select_data:
      _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: src/schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: true
        remove_extra_inputs: false
        icon: notes
        _editables:
        _inputs:
        _select_data:
        _structures:
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Blocks
    collections:
      - blocks
_inputs:
  pages:
    type: multiselect
    options:
      preview:
        text:
          - key: url
    label: Categorieën
    cascade: true
  head:
    type: auto
    label: SEO
    cascade: true
  head.title:
    type: auto
    label: Pagina title
    comment: 50 tot 60 karakters
    cascade: true
  head.description:
    type: auto
    label: Pagina beschrijving
    comment: 50 tot 120 karakters
    cascade: true
  head.image:
    type: auto
    label: Pagina afbeelding
    comment: Zichtbaar wanneer de pagina wordt gedeeld op social media
    cascade: true
  src:
    type: image
    options:
      expandable: false
      mime_type: image/webp
      correct_orientation: false
      prevent_resize_existing_files: true
      resize_style: crop
    label: Afbeelding
    cascade: true
  href:
    type: url
    label: Link
    cascade: true
  rating:
    type: range
    options:
      min: 0
      max: 5
      step: 0.1
    label: Rating
    cascade: true
  images:
    type: array
    cascade: true
  images[*]:
    type: image
    cascade: true
  draft:
    type: switch
    label: Concept
    cascade: true
  variant:
    type: auto
    hidden: true
    cascade: true
  price:
    type: number
    cascade: true
  paragraph:
    type: textarea
    cascade: true
_structures:
  blocks:
    remove_empty_inputs: true
_editables:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    bold: true
    bulletedlist: true
    format: p h1 h2 h3 h4 h5 h6
    image: true
    image_size_attributes: true
    italic: true
    link: true
    numberedlist: true
    redo: true
    table: true
    underline: true
    undo: true
timezone: Europe/Amsterdam
