const headerBlockNames = [
  "banner-1",
  "banner-2",
  "header-1",
  "header-2",
  "header-3",
]

const footerBlockNames = ["footer-1", "footer-2"]

const sectionBlockNames = [
  "article-1",
  "article-2",
  "articles-1",
  "articles-2",
  "articles-3",
  "articles-4",
  "contact-1",
  "contact-2",
  "contact-3",
  "content-1",
  "content-2",
  "content-3",
  "content-4",
  "content-5",
  "content-6",
  "cta-1",
  "cta-2",
  "cta-3",
  "cta-4",
  "cta-5",
  "cta-6",
  "cta-7",
  "cta-8",
  "faqs-1",
  "faqs-2",
  "faqs-3",
  "faqs-4",
  "features-1",
  "features-2",
  "features-3",
  "features-4",
  "features-5",
  "features-6",
  "hero-1",
  "hero-2",
  "hero-3",
  "hero-4",
  "hero-5",
  "hero-6",
  "hero-7",
  "hero-8",
  "hero-9",
  "hero-10",
  "hero-11",
  "hero-12",
  "hero-13",
  "logos-1",
  "logos-2",
  "logos-3",
  "pricings-1",
  "pricings-2",
  "pricings-3",
  "product-1",
  "products-1",
  "products-2",
  "products-3",
  "products-4",
  "products-5",
  "reviews-1",
  "reviews-2",
  "reviews-3",
  "reviews-4",
  "reviews-5",
  "services-1",
  "services-2",
  "services-3",
  "services-4",
  "services-5",
  "services-6",
  "services-7",
]

const allBlockNames = [
  ...headerBlockNames,
  ...footerBlockNames,
  ...sectionBlockNames,
]

export { allBlockNames, footerBlockNames, headerBlockNames, sectionBlockNames }
