spec:
  structures:
    - blocks
    - content
  label: Content

blueprint:
  heading:
  text:
  buttons:
    - text:
      href:

preview:
  heading: Hello worldddd
  text: Lorem ipsum
  buttons:
    - text: Button
      href: /
    - text: Button
      href: /

_inputs:
