spec:
  structures:
    - blocks
  label: Features

blueprint:
  heading:
  text:
  buttons:
    - text:
      href:
  cards:
    - icon:
      heading:
      text:

preview:
  heading: Fulldev-starter
  text: Get started with fulldev-starter by editing this page in src/content/pages/index.md.
  buttons:
    - text: Click me
      href: /
  cards:
    - icon: circle
      heading: Feature 1
      text: Lorem ipsum dolor sit amet
    - icon: circle
      heading: Feature 1
      text: Lorem ipsum dolor sit amet
    - icon: circle
      heading: Feature 1
      text: Lorem ipsum dolor sit amet

_inputs:
