seo:
  image: images/og-image.png

sidebar: false
toc: false
themeselect: true

header:
  company: fulldev-starter
  buttons:
    - text: Home
      href: /
    - about
    - text: Blog
      href: '/blog'
    - text: About
      href: '/about'
    - text: Team
      href: '/team'
    - text: Projects
      href: '/projects'
    - text: Services
      href: '/services'
    - text: Testimonials
      href: '/testimonials'
    - text: Contact
      href: '/contact'
    - text: Guide
      href: 'https://github.com/fulldotdev/starter/blob/main/README.md'
    - icon: brand-github
      href: 'https://github.com/fulldotdev/starter'
      variant: secondary
    - icon: layout
      text: UI/Blocks
      variant: secondary
      href: 'https://ui.full.dev'
  drawer:
    links:
      - text: Home
        href: '/'
      - text: About
        href: '/about'
      - text: Blog
        href: '/blog'
      - text: Products
        href: '/products'
      - text: Contact
        href: '/contact'
      - icon: brand-github
        href: 'https://github.com/fulldotdev/starter'
      - icon: UI/Blocks Library
        href: 'https://ui.full.dev'
      - text: Guide
        href: 'https://github.com/fulldotdev/starter/blob/main/README.md'

footer:
  company: fulldev-starter
  text: Supercharging content-driven website development
  columns:
    - heading: Example Pages
      buttons:
        - text: Home
          href: /
        - text: About
          href: '/about'
        - text: Team
          href: '/team'
        - text: Projects
          href: '/projects'
        - text: Services
          href: '/services'
        - text: Testimonials
          href: '/testimonials'
        - text: Contact
          href: '/contact'

    - heading: Resources
      buttons:
        - text: Home
          href: /
        - text: Components
          href: 'https://ui.full.dev/typography/heading/'
        - text: Blocks
          href: 'https://ui.full.dev/blocks/banner'
        - text: README
          href: 'https://github.com/fulldotdev/starter/blob/main/README.md'
